name: 'Say Hello with LLM'
on:
  pull_request:

jobs:
  say-hello:
    permissions:
      models: read
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Run AI Inference with fixed prompt
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: "こんにちわ!!!!!!!!!"

      - name: Comment on PR
        env:
          RESPONSE: ${{ steps.inference.outputs.response }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ env.RESPONSE }}" > comment.txt
          gh pr comment ${{ github.event.pull_request.number }} --body-file comment.txt

# name: 'Review with LLM'
# on: 
#   pull_request:
#     paths:
#       - notebooks/**/*.ipynb
 
# jobs:
#   review:
#     permissions:
#       models: read
#       # ファイルをプロンプトとして渡すために必要な権限
#       contents: read
#       pull-requests: write
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
#         with:
#           fetch-depth: 0
 
#       # 変更されたファイルを取得する
#       - name: Get changed files in the contents folder
#         id: changed-files-specific
#         uses: tj-actions/changed-files@4cd184a1dd542b79cca1d4d7938e4154a6520ca7 # v46.0.0
#         with:
#           files: |
#             notebooks/**/*.ipynb

#       # プロンプトを1ファイルに結合（システムプロンプト＋差分ファイル）
#       - name: Build full prompt with system prompt and changed files
#         id: concat
#         if: steps.changed-files-specific.outputs.all_changed_files != ''
#         run: |
#           mkdir -p tmp
          
#           echo "## Notebook Coding Guidelines" > tmp/combined_prompt.txt
#           echo "" >> tmp/combined_prompt.txt
#           cat notebook-coding-guidelines.md >> tmp/combined_prompt.txt
#           echo -e "\n\n---\n\n" >> tmp/combined_prompt.txt

#           files="${{ steps.changed-files-specific.outputs.all_changed_files }}"
#           for f in $files; do
#             echo "# FILE: $f" >> tmp/combined_prompt.txt
#             cat "$f" >> tmp/combined_prompt.txt
#             echo -e "\n\n" >> tmp/combined_prompt.txt
#           done

#           echo "prompt_file=tmp/combined_prompt.txt" >> $GITHUB_OUTPUT

#       - name: Run AI Inference with combined prompt
#         id: inference
#         uses: actions/ai-inference@f8ee4c952b7dca7b8a4529edd04dc5cc3d49c435
#         if: steps.concat.outputs.prompt_file != ''
#         with:
#           prompt-file: ${{ steps.concat.outputs.prompt_file }}

#       - name: Comment on PR
#         id: comment
#         if: steps.inference.outputs.response != ''
#         env:
#           RESPONSE: ${{ steps.inference.outputs.response }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           echo "${{ env.RESPONSE }}" > comment.txt
#           gh pr comment ${{ github.event.pull_request.number }} --body-file comment.txt
#           echo "Commented on PR #${{ github.event.pull_request.number }} with response: ${{ env.RESPONSE }}"
