name: 'Review with LLM'
on: 
  pull_request:
    paths:
      - notebooks/**/*.ipynb
 
jobs:
  review:
    permissions:
      models: read
      # ファイルをプロンプトとして渡すために必要な権限
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
 
      - name: Set up Jupyter nbconvert
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert

      # 変更されたファイルを取得する
      - name: Get changed files in the contents folder
        id: changed-files-specific
        uses: tj-actions/changed-files@4cd184a1dd542b79cca1d4d7938e4154a6520ca7 # v46.0.0
        with:
          files: |
            notebooks/**/*.ipynb

      # プロンプトを1ファイルに結合（システムプロンプト＋差分ファイル）
      - name: Build full prompt with system prompt and changed files
        id: concat
        if: steps.changed-files-specific.outputs.all_changed_files != ''
        run: |
          mkdir -p tmp
          
          echo "## Notebook Coding Guidelines" > tmp/combined_prompt.txt
          echo "" >> tmp/combined_prompt.txt
          cat notebook-coding-guidelines.md >> tmp/combined_prompt.txt
          echo -e "\n\n---\n\n" >> tmp/combined_prompt.txt

          files="${{ steps.changed-files-specific.outputs.all_changed_files }}"
          for f in $files; do
            jupyter nbconvert --ClearOutputPreprocessor.enabled=True --to notebook --inplace "$f"
            echo "# FILE: $f" >> tmp/combined_prompt.txt
            cat "$f" >> tmp/combined_prompt.txt
            echo -e "\n\n" >> tmp/combined_prompt.txt
          done

          echo "prompt_file=tmp/combined_prompt.txt" >> $GITHUB_OUTPUT

      - name: Run AI Inference with combined prompt
        id: inference
        uses: actions/ai-inference@f8ee4c952b7dca7b8a4529edd04dc5cc3d49c435
        if: steps.concat.outputs.prompt_file != ''
        with:
          system-prompt: |
            あなたは、Jupyter Notebookのコードレビューを行うずんだの妖精です。以下のNotebookのコードを"Notebook Coding Guidelines"に基づく観点からレビューし、改善点や提案をコメントしてください。
            レビューの出力は日本語で行い、更に文末には「〜なのだ。」「〜のだ。」をつけて話します。
          prompt-file: ${{ steps.concat.outputs.prompt_file }}
          max-tokens: 2000

      - name: Comment on PR
        id: comment
        if: steps.inference.outputs.response-file != ''
        env:
          RESPONSE_FILE: ${{ steps.inference.outputs.response-file }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::group::Inference response"
          cat ${{ env.RESPONSE_FILE }}
          echo "::endgroup::"

          gh pr comment ${{ github.event.pull_request.number }} --body-file ${{ env.RESPONSE_FILE }}
          echo "Commented on PR #${{ github.event.pull_request.number }} with response: ${{ env.RESPONSE_FILE }}"
